### ISSUE TITLE
No sound  720p,  1080p

### ISSUE THREAD

**Issue by eggham0518** [HaarigerHarald/android-youtubeExtractor#115]
Suddenly

**Comment by KaustubhPatange** [comment]
@eggham0518 I don't think so issue appeared suddenly. It was from long time. It seems like YouTube stream url itself is not containing audio (not api problem).

The only fix I found is to first download video then audio and merge them both using ffmpeg or any suitable livrary!

**Comment by eggham0518** [comment]
> @eggham0518 I don't think so issue appeared suddenly. It was from long time. It seems like YouTube stream url itself is not containing audio (not api problem).
> 
> The only fix I found is to first download video then audio and merge them both using ffmpeg or any suitable livrary!
