### ISSUE TITLE
get url return null

### ISSUE THREAD

**Issue by M1Dr05** [HaarigerHarald/android-youtubeExtractor#117]
From today all URL extraction return null.
Sample video: https://www.youtube.com/watch?v=zqUopiAYdRg

**Comment by mrhussnain** [comment]
i have solution contact me at mrhussnain3@gmail.com

**Comment by sseodate** [comment]
i dont have whatsapp, do you have skype or fb?

**Comment by smsmathan** [comment]
Am contacted you with excited.. but you are not helped me... If you really
teach and share if you really open minded ... Don't ask money  for changing
small things .. am asked fixing for your old version only not an new api
...

**Comment by mrhussnain** [comment]
@smsmathan  dear I guide you properly but I cant develop the app for you free you are saying to implement free API for on your app lol... I helped you I give you free my API you can use it if you have a coding idea if you don't have then you have to pay or go hire any other freelancer nothing is free I helped you and guided you that is enough not everything is free.

**Comment by mrhussnain** [comment]
> i dont have whatsapp, do you have skype or fb?

live:5f32240ef0c1d798

Skype Live ID

**Comment by bunaif** [comment]
@M1Dr05  everything okay, this URL [https://www.youtube.com/watch?v=zqUopiAYdRg](https://www.youtube.com/watch?v=zqUopiAYdRg)   work fine

**Comment by M1Dr05** [comment]
> @M1Dr05 everything okay, this URL https://www.youtube.com/watch?v=zqUopiAYdRg work fine

if it returned to normal.
