### ISSUE TITLE
Array YtFile always null

### ISSUE THREAD

**Issue by clclon** [HaarigerHarald/android-youtubeExtractor#150]
Hi, returned array YtFile always null, Meta is not empty:

```
=VideoMeta{
  videoId='2mY7AFTtYwQ',
  title='Camilo - Favorito (Official Video)',
  author='CamiloVEVO',
  channelId='UCXQIVincj_W4CYfWKB1iPVQ',
  videoLength=210,
  viewCount=200920636,
  isLiveStream=false}
```
Version v2.1.0

**Comment by xibr** [comment]
Now it works without any problem!

**Comment by clclon** [comment]
No, unfortunately it doesn’t work, maybe the platform - the AndroidTV API24 emulator somehow influences it.  Any youtube url behaves the same way, including those mentioned in other discussions on this project.

The code is typical, from the example.  if I can help with the solution of this problem, let me know, I am ready to conduct various tests.

**Comment by HaarigerHarald** [comment]
Don't use the latest release, use com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT instead, the release is outdated

**Comment by clclon** [comment]
Yes, thanks, the snapshot version worked fine.  The releases are confused, or rather their numbers :) it would be more reasonable to remove them altogether from the public domain - they introduce confusion.
