### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by Dolanpls** [HaarigerHarald/android-youtubeExtractor#160]
@HaarigerHarald you have >100 issues and 3 open PR
You don't do nothing because think that are not important or this repo is abandoned?

**Comment by Dolanpls** [comment]
I'm going to assume yes :(

**Comment by maciejbudzyn** [comment]
Author did a great job creating this library but apparently has no more time for updates and maintenance. 
I guess we can assume it is abandoned. 
If you need some alternative, check it: https://github.com/kotvertolet/youtube-jextractor. In my app I'm using now jextractor as main extractor library and youtubeExtractor as secondary (if first has failed).
