### ISSUE TITLE
In my android app I was using 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT' to get the youtube URL to play the video in exoplayer. But for 2 or 3 days it is unable to give the URL.  Code below-      @SuppressLint("StaticFieldLeak")     YouTubeExtractor mExtractor = new YouTubeExtractor(this) {         @Override         protected void onExtractionComplete(SparseArray<YtFile> sparseArray, VideoMeta videoMeta) {             if (sparseArray != null) {                 url = sparseArray.get(18).getUrl();                 Log.i("VIDEO_URL", url);                 initializePlayer();             }         }     };      mExtractor.extract(mYoutubeLink, false, true);

### ISSUE THREAD

**Issue by rajnesh-culturealley** [HaarigerHarald/android-youtubeExtractor#175]

**Comment by Akarsh07** [comment]
The same happens to me.

**Comment by shailendra-rajpoot** [comment]
i am getting same issue

**Comment by gajananinfotech20** [comment]
BasicNetwork.performRequest: Unexpected response code 403 for http://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=30Y6QnAumWw
E/erorr::: com.android.volley.AuthFailureError

**Comment by ajstar12** [comment]
My All Live Project Getting Same Here.

**Comment by shailendra-rajpoot** [comment]
how to pass this parameter html5=1 in my method
extractYoutubeUrl()

extractYoutubeUrl("https://www.youtube.com/watch?v=$id",iTag.toInt(),::getDecodedUrl)

**Comment by shailendra-rajpoot** [comment]
how to pass this parameter html5=1 in my method
extractYoutubeUrl()

extractYoutubeUrl("https://www.youtube.com/watch?v=$id",iTag.toInt(),::getDecodedUrl)

**Comment by shailendra-rajpoot** [comment]
please bro tell me how can fix the issue
how can i  pass this parameter html5=1 in my method
extractYoutubeUrl()

extractYoutubeUrl("https://www.youtube.com/watch?v=$id",iTag.toInt(),::getDecodedUrl)
