### ISSUE TITLE
html5=1 is not working.

### ISSUE THREAD

**Issue by Abhay-cloud** [HaarigerHarald/android-youtubeExtractor#185]
Before 2 days everything was working fine.
But from yesterday I have found that out of 5 tries (5 clicks on download button) for the same video link, it works for only 2 time.
When I click first time it does not work. It throws "java.io.FileNotFoundException: https://www.youtube.com/get_video_info?html5=1&video_id=rw9xDQRNQWY&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2Frw9xDQRNQWY" 
then when I click 4 - 5 more times on button for the same link then it works for last 2 clicks.

**Comment by gajananinfotech20** [comment]
Same issue please share solution

**Comment by qyzhaojinxi** [comment]
I also met this problem.

**Comment by pongsatornw** [comment]
Yesterday, I can play video sometimes, but now it not play even once.

**Comment by shailendra-rajpoot** [comment]
same problem

**Comment by qyzhaojinxi** [comment]
I found this can work. You can try it.

https://stackoverflow.com/a/67629882/3064153

and I found this way in this link:

https://github.com/yuliskov/MediaServiceCore/blob/f80d523fb16934cdd00f99de269c025cd24d0b5d/youtubeapi/src/test/resources/youtube-requests.http

**Comment by quanctdev** [comment]
Thanks @qyzhaojinxi

**Comment by shailendra-rajpoot** [comment]
hi friend i am beginner I could not understand you. how did you solve it plz share code if possible.

**Comment by shailendra-rajpoot** [comment]
hi friend i am beginner I could not understand you. how did you solve it plz share code if possible.

**Comment by shailendra-rajpoot** [comment]
html5=1 this is added but it not work too

**Comment by shailendra-rajpoot** [comment]
@quanctdev plz tell me how are your  code is working ?

**Comment by shailendra-rajpoot** [comment]
Plz bro tell how your code is working plz share with me if possible

**Comment by shailendra-rajpoot** [comment]
Hi bro i am not understanding you plz share code with me if possible.

**Comment by papcai** [comment]
@shailendra-rajpoot add more c=TVHTML5&cver=6.20180913

**Comment by shailendra-rajpoot** [comment]
@papcai  thanks bro it work nice.

**Comment by thisistorsten** [comment]
https://github.com/snakx/YouTubeApiSharp/commit/e0432b36f7416974548d56f33e27a48576b36e98

**Comment by Abhay-cloud** [comment]
> @shailendra-rajpoot add more c=TVHTML5&cver=6.20180913

@papcai @shailendra-rajpoot Do we have to add it to video url?

**Comment by qyzhaojinxi** [comment]
> Thanks @qyzhaojinxi

You're wecome.

**Comment by thisistorsten** [comment]
No. The get_video_info endpoint is dead. It doesent include needed
informations anymore. It needs a refactoring of code like this one here
https://github.com/snakx/YouTubeApiSharp

I already fixed it.

Abhay ***@***.***> schrieb am Sa., 19. Juni 2021, 11:54:

**Comment by SushilBerwal** [comment]
> @shailendra-rajpoot add more c=TVHTML5&cver=6.20180913

After added this parameter .m3u8 url not getting please help
