### ISSUE TITLE
decipherSignature is returning null

### ISSUE THREAD

**Issue by amitec07** [HaarigerHarald/android-youtubeExtractor#200]
decipherSignature() is broken and getting null from two days. it seems patSignatureDecFunction is not matching. Pleasefix it as soon as possible.

thanks

**Comment by trantrung22** [comment]
Yes, got the same error, psl check the regex in youtube-dl for reference

**Comment by amitec07** [comment]
Latest update fixed the problem, thank you for the quick fix.
