### ISSUE TITLE
Failed to resolve: com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT

### ISSUE THREAD

**Issue by BatuhanAkar** [HaarigerHarald/android-youtubeExtractor#235]
Now I can't find it in the repository, and furthermore, when I manually specify the latest version as v2.1.0, the issue is resolved. However, now the video links are consistently empty and I receive an HTTP ERROR 410. How can I resolve this? It used to work correctly before.

master-SNAPSHOT warning/error

Failed to resolve: com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT
Show in Project Structure dialog
Affected Modules: app

-----

v2.1.0 error

`the link provided to execute :: https://www.youtube.com/watch?v=oCxtsTU4BWg`

16:52:51.000  D  app_time_stats: avg=4336.91ms min=4336.91ms max=4336.91ms count=1
**16:52:51.054  W  java.io.FileNotFoundException: https://www.youtube.com/get_video_info?video_id=oCxtsTU4BWg&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FoCxtsTU4BWg**
16:52:51.054  W  	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
16:52:51.054  W  	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
16:52:51.055  W  	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
16:52:51.055  W  	at at.huber.youtubeExtractor.YouTubeExtractor.getStreamUrls(YouTubeExtractor.java:219)
16:52:51.055  W  	at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:195)
16:52:51.055  W  	at at.huber.youtubeExtractor.YouTubeExtractor.doInBackground(YouTubeExtractor.java:34)
16:52:51.055  W  	at android.os.AsyncTask$3.call(AsyncTask.java:394)
16:52:51.055  W  	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
16:52:51.055  W  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
16:52:51.055  W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
16:52:51.056  W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
16:52:51.056  W  	at java.lang.Thread.run(Thread.java:1012)
16:52:51.106  I  YTfile null... <-- /// comment line

**Comment by BatuhanAkar** [comment]
any solution ??

**Comment by BatuhanAkar** [comment]
i'm using the latest version v2.1.0 but still the old user agent settings , and the file is opened only in reading mode.

how can i fix it ???

` private static final String USER_AGENT = "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36";`

**Comment by ThreeMinutesFix** [comment]
for now use 
implementation 'com.github.HaarigerHarald:android-youtubeExtractor:v2.1.0'
this when you get error on this change back to SNAPSHOT  implementation. if you want permeenent fix add this as module in your project thats the only way other way this lib owner has to fix

**Comment by BatuhanAkar** [comment]
> for now use implementation 'com.github.HaarigerHarald:android-youtubeExtractor:v2.1.0' this when you get error on this change back to SNAPSHOT implementation. if you want permeenent fix add this as module in your project thats the only way other way this lib owner has to fix

thanks. it solved my problem of including the module directly into the project.
