### ISSUE TITLE
Move to new Youtube-Extractor library

### ISSUE THREAD

**Issue by Rider02vn** [HaarigerHarald/android-youtubeExtractor#238]
Hi.
This library has been discontinued and has not been maintained for a long time.
Please use new **Youtube-Extractor** library .
It's perect working
[https://github.com/Rider02vn/Youtube-Extractor](https://github.com/Rider02vn/Youtube-Extractor)

**Comment by Mathias8405** [comment]
> Hi. This library has been discontinued and has not been maintained for a long time. Please use new **Youtube-Extractor** library . It's perect working https://github.com/Rider02vn/Youtube-Extractor

What dependencies do you use for this? I want to use this code in a Kotlin app for Android

**Comment by Rider02vn** [comment]
> > Hi. This library has been discontinued and has not been maintained for a long time. Please use new **Youtube-Extractor** library . It's perect working https://github.com/Rider02vn/Youtube-Extractor
> 
> What dependencies do you use for this? I want to use this code in a Kotlin app for Android

@Mathias8405 Please contact:
Mail: [rider02vn@gmail.com](mailto:rider02vn@gmail.com)
Skype: [Click here](https://join.skype.com/invite/b1NHI8Dv1zrz)

**Comment by fiasko131** [comment]
@Mathias8405 
It seems that recently a change in the youtube share url has appeared.
You must therefore make this modification to the URL of the share:
````java
if (YTsharedUrl.contains("watch?v=watch?v=")){
       YTsharedUrl= YTsharedUrl.replace("watch?v=watch?v=","watch?v=");
}
````
Paid library posted by  @Rider02vn   "https://github.com/Rider02vn/Youtube-Extractor" is a scam!!

**Comment by Rider02vn** [comment]
> @Mathias8405 It seems that recently a change in the youtube share url has appeared. You must therefore make this modification to the URL of the share:
> 
> ```java
> if (YTsharedUrl.contains("watch?v=watch?v=")){
>        YTsharedUrl= YTsharedUrl.replace("watch?v=watch?v=","watch?v=");
> }
> ```
> 
> Paid library posted by @Rider02vn "https://github.com/Rider02vn/Youtube-Extractor" is a scam!!

Humm.
Please submit proof.
Don't slander others like that.

**Comment by Mathias8405** [comment]
> @Mathias8405 It seems that recently a change in the youtube share url has appeared. You must therefore make this modification to the URL of the share:
> 
> ```java
> if (YTsharedUrl.contains("watch?v=watch?v=")){
>        YTsharedUrl= YTsharedUrl.replace("watch?v=watch?v=","watch?v=");
> }
> ```
> 
> Paid library posted by @Rider02vn "https://github.com/Rider02vn/Youtube-Extractor" is a scam!!

Yeah, I figured it was a scam. Plus, I refuse to pay for a library that was initially free especially at a price gouging price. So, the share link is the download link?

**Comment by fiasko131** [comment]
The link returned to be used by the extractor is the link that is given (under android) by sharing the video.
Recently it is not in the form: https://www.youtube.com/watch?v=watch?v=FzWGvx1pmFA&feature=share.
Mais il doit être modifié comme ceci:
https://www.youtube.com/watch?v=FzWGvx1pmFA&feature=share.

**Comment by Rider02vn** [comment]
We sell because we put effort and time into researching and coding the library.  Our library is different from this one. What's wrong with that?  You want everything to be free for you to use?

We have never scammed anyone. If accusing us of fraud please provide a video to prove it.

We are also ready to demo to prove our library is still working properly.  And those who slander us are petty, lowly, very disgraceful people.

**Comment by fiasko131** [comment]
@Rider02vn 
The proof is that I can still get the audio and video URLs.
So contrary to what you say this library continues to work if we take care to check the sharing URL or we must delete the duplicate "watch?v=".
Your super expensive proposal is therefore a scam here on github.

**Comment by Rider02vn** [comment]
> Liên kết được trình giải nén trả lại để sử dụng là liên kết được cung cấp (trong android) bằng cách chia sẻ video. Gần đây nó không ở dạng: https://www.youtube.com/watch?v=watch?v=FzWGvx1pmFA&feature=share . Mais il doit être modifié comme ceci: https://www.youtube.com/watch?v=FzWGvx1pmFA&feature=share .

Who are you ? Why slander us?
Take a video to prove we're a scam and upload it here. Don't lie without proof. You are a failure, an evil person.

**Comment by fiasko131** [comment]
Ok, so immediately give your prices for this library that we laugh!!

**Comment by fiasko131** [comment]
You say : "This library has been discontinued and has not been maintained for a long time."

It's simply false!!

**Comment by Rider02vn** [comment]
> Ok, so immediately give your prices for this library that we laugh!!

What does the price have to do with you slandering us?

**Comment by fiasko131** [comment]
Your prices: 
"We have built the source code into a library, which you can easily integrate into your project.
There are 2 option of payment:
1. Subscription (Get stream through our server, used for 1 app, extra 30$/month for every next app):
+ 300$ for 3 months
+ 550$ for 6 months
+ 1050$ for 12 months
2. Pro (We provide the full source code library, get the stream directly to the Youtube server, so the speed will be faster and more stable, no limit to the number of apps used):
1500$"
:((
No comment!

**Comment by Mathias8405** [comment]
> @Mathias8405 It seems that recently a change in the youtube share url has appeared. You must therefore make this modification to the URL of the share:
> 
> ```java
> if (YTsharedUrl.contains("watch?v=watch?v=")){
>        YTsharedUrl= YTsharedUrl.replace("watch?v=watch?v=","watch?v=");
> }
> ```
> 
> Paid library posted by @Rider02vn "https://github.com/Rider02vn/Youtube-Extractor" is a scam!!

This library is using YouTubeExtractor constructor in the library. How are you getting YTShareUrl as your library constructor? We maybe using different library dependencies?

**Comment by Mathias8405** [comment]
> @Mathias8405 It seems that recently a change in the youtube share url has appeared. You must therefore make this modification to the URL of the share:
> 
> ```java
> if (YTsharedUrl.contains("watch?v=watch?v=")){
>        YTsharedUrl= YTsharedUrl.replace("watch?v=watch?v=","watch?v=");
> }
> ```
> 
> Paid library posted by @Rider02vn "https://github.com/Rider02vn/Youtube-Extractor" is a scam!!

This library is using YouTubeExtractor constructor in the library. How are you getting YTShareUrl as your library constructor? We maybe using different library dependencies?

**Comment by Rider02vn** [comment]
**What a bad guy, a failure.**

![Screenshot_20230817_215713_Skype](https://github.com/HaarigerHarald/android-youtubeExtractor/assets/92910283/0425b730-7e94-4156-8f85-3c056c862c17)

**Comment by fiasko131** [comment]
The url you need to use for the extractor must be a share url on android. Which you retrieve with an intent to your application. This url must be in this form: " https://www.youtube.com/watch?v=FzWGvx1pmFA&feature=share"

Then you use it to extract the links to the sound or video depending on the itag.

Comme ceci : 
````java
new YouTubeExtractor(activity) {
                                                    @Override
                                                    public void onExtractionComplete(SparseArray<YtFile> ytFiles, VideoMeta vMeta) {
                                                        if (ytFiles != null) {
                                                           
                                                            int itag = 140; // for audio only

                                                            playableURL = ytFiles.get(itag).getUrl();
                                                            yoututubeThumbUrl = vMeta.getThumbUrl();
                                                            youtubeTitle = vMeta.getTitle();
                                                            

                                                        }
                                                    }
                                                }.extract("yourYouTubeSharedUrl");
````

**Comment by Mathias8405** [comment]
> The url you need to use for the extractor must be a share url on android. Which you retrieve with an intent to your application. This url must be in this form: " https://www.youtube.com/watch?v=FzWGvx1pmFA&feature=share"
> 
> Then you use it to extract the links to the sound or video depending on the itag.
> 
> Comme ceci :
> 
> ```java
> new YouTubeExtractor(activity) {
>                                                     @Override
>                                                     public void onExtractionComplete(SparseArray<YtFile> ytFiles, VideoMeta vMeta) {
>                                                         if (ytFiles != null) {
>                                                            
>                                                             int itag = 140; // for audio only
> 
>                                                             playableURL = ytFiles.get(itag).getUrl();
>                                                             yoututubeThumbUrl = vMeta.getThumbUrl();
>                                                             youtubeTitle = vMeta.getTitle();
>                                                             
> 
>                                                         }
>                                                     }
>                                                 }.extract("yourYouTubeSharedUrl");
> ```

Thanks!

**Comment by fiasko131** [comment]
> **What a bad guy, a failure.**
> 
> ![Screenshot_20230817_215713_Skype](https://user-images.githubusercontent.com/92910283/261351675-0425b730-7e94-4156-8f85-3c056c862c17.jpg)

You are pathetic!!!

**Comment by Rider02vn** [comment]
We do not welcome people who just want to use it for free, do not acknowledge the work of others.
Close at here

**Comment by Mathias8405** [comment]
It's not always about money you greedy bastard! We can acknowledge others by
saying thank you! That's good enough! You can take your library and your
greedy price gouging prices elsewhere!
