### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by akashpopat** [HaarigerHarald/android-youtubeExtractor#27]
Hi
Since the last 12+hours the library isn't working. ytFiles always returns null.

`03-07 23:38:59.902 16995-18036/com.akashpopat W/System.err: java.util.regex.PatternSyntaxException: Incorrectly nested parentheses in regexp pattern near index 13:
03-07 23:38:59.906 16995-18036/com.akashpopat W/System.err: (var |)f.sig):f.s&&k.set(=function\((.{1,3})\)\{)
03-07 23:38:59.910 16995-18036/com.akashpopat. W/System.err:              ^
03-07 23:38:59.918 16995-18036/com.akashpopat. W/System.err:     at java.util.regex.Pattern.compileImpl(Native Method)
03-07 23:38:59.923 16995-18036/com.akashpopat. W/System.err:     at java.util.regex.Pattern.compile(Pattern.java:411)
03-07 23:38:59.927 16995-18036/com.akashpopat. W/System.err:     at java.util.regex.Pattern.<init>(Pattern.java:394)
03-07 23:38:59.932 16995-18036/com.akashpopat. W/System.err:     at java.util.regex.Pattern.compile(Pattern.java:381)
03-07 23:38:59.935 16995-18036/com.akashpopat. W/System.err:     at at.huber.youtubeExtractor.YouTubeUriExtractor.decipherSignature(YouTubeUriExtractor.java:402)
03-07 23:38:59.939 16995-18036/com.akashpopat. W/System.err:     at at.huber.youtubeExtractor.YouTubeUriExtractor.getStreamUrls(YouTubeUriExtractor.java:320)
03-07 23:38:59.948 16995-16995/com.akashpopat. W/Ads: The webview is destroyed. Ignoring action.
03-07 23:38:59.955 16995-18036/com.akashpopat. W/System.err:     at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:158)
03-07 23:38:59.960 16995-18036/com.akashpopat. W/System.err:     at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:32)
03-07 23:38:59.963 16995-18036/com.akashpopat. W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-07 23:38:59.966 16995-18036/com.akashpopat. W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-07 23:38:59.970 16995-18036/com.akashpopat. W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-07 23:38:59.973 16995-18036/com.akashpopat. W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-07 23:38:59.976 16995-18036/com.akashpopat. W/System.err:     at java.lang.Thread.run(Thread.java:818)`

**Comment by danilaplee** [comment]
+1, confirming bug, here is my debug log
TRYING TO GET YOUTUBE: http://www.youtube.com/embed/nJDbQIrbj8o
03-08 18:51:10.137 10758 10758 E ID:     : nJDbQIrbj8o
03-08 18:51:10.138 10758 10758 E VIDEO_FILES: NULL
03-08 18:51:10.138 10758 10758 E VIDEO_FILES: RETRYING
03-08 18:51:10.398   871   871 E WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 97 num clients 9
03-08 18:51:10.399   871   871 E WifiTrafficPoller:  packet count Tx=501259 Rx=2267676
03-08 18:51:10.967   871  1197 E WifiConfigStore: updateConfiguration freq=2462 BSSID=d0:d0:4b:66:db:e8 RSSI=-43 "HomeVR"WPA_PSK
03-08 18:51:11.208 10758 10818 W System.err: java.util.regex.PatternSyntaxException: Incorrectly nested parentheses in regexp pattern near index 19:
03-08 18:51:11.208 10758 10818 W System.err: (var |\s|,|;)f.sig):f.s&&k.set(=function\((.{1,3})\)\{)
03-08 18:51:11.208 10758 10818 W System.err:                    ^
03-08 18:51:11.208 10758 10818 W System.err: 	at java.util.regex.Pattern.compileImpl(Native Method)
03-08 18:51:11.208 10758 10818 W System.err: 	at java.util.regex.Pattern.compile(Pattern.java:411)
03-08 18:51:11.209 10758 10818 W System.err: 	at java.util.regex.Pattern.<init>(Pattern.java:394)
03-08 18:51:11.209 10758 10818 W System.err: 	at java.util.regex.Pattern.compile(Pattern.java:381)
03-08 18:51:11.209 10758 10818 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.decipherSignature(YouTubeUriExtractor.java:402)
03-08 18:51:11.209 10758 10818 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.getStreamUrls(YouTubeUriExtractor.java:320)
03-08 18:51:11.209 10758 10818 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:158)
03-08 18:51:11.211 10758 10818 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:32)
03-08 18:51:11.211 10758 10818 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-08 18:51:11.211 10758 10818 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-08 18:51:11.211 10758 10818 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-08 18:51:11.211 10758 10818 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-08 18:51:11.211 10758 10818 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-08 18:51:11.211 10758 10818 W System.err: 	at java.lang.Thread.run(Thread.java:818)
03-08 18:51:11.212 10758 10758 E TRYING TO GET YOUTUBE: http://www.youtube.com/embed/nJDbQIrbj8o
03-08 18:51:11.212 10758 10758 E ID:     : nJDbQIrbj8o
03-08 18:51:11.212 10758 10758 E VIDEO_FILES: NULL
03-08 18:51:11.213 10758 10758 E VIDEO_FILES: RETRYING
03-08 18:51:11.380  1505  9943 W ctxmgr  : [AclManager]No 2 for (accnt=account#703349407#, com.google.android.gms(10009):UserLocationProducer, vrsn=10298000, 0, 3pPkg = null ,  3pMdlId = null). Was: 2 for 1, account#703349407#
03-08 18:51:11.400   871   871 E WifiTrafficPoller: TRAFFIC_STATS_POLL true Token 97 num clients 9
03-08 18:51:11.400   871   871 E WifiTrafficPoller:  packet count Tx=501370 Rx=2268026
03-08 18:51:12.239 10758 10822 W System.err: java.util.regex.PatternSyntaxException: Incorrectly nested parentheses in regexp pattern near index 19:
03-08 18:51:12.240 10758 10822 W System.err: (var |\s|,|;)f.sig):f.s&&k.set(=function\((.{1,3})\)\{)
03-08 18:51:12.240 10758 10822 W System.err:                    ^
03-08 18:51:12.241 10758 10822 W System.err: 	at java.util.regex.Pattern.compileImpl(Native Method)
03-08 18:51:12.241 10758 10822 W System.err: 	at java.util.regex.Pattern.compile(Pattern.java:411)
03-08 18:51:12.241 10758 10822 W System.err: 	at java.util.regex.Pattern.<init>(Pattern.java:394)
03-08 18:51:12.241 10758 10822 W System.err: 	at java.util.regex.Pattern.compile(Pattern.java:381)
03-08 18:51:12.242 10758 10822 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.decipherSignature(YouTubeUriExtractor.java:402)
03-08 18:51:12.242 10758 10822 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.getStreamUrls(YouTubeUriExtractor.java:320)
03-08 18:51:12.242 10758 10822 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:158)
03-08 18:51:12.242 10758 10822 W System.err: 	at at.huber.youtubeExtractor.YouTubeUriExtractor.doInBackground(YouTubeUriExtractor.java:32)
03-08 18:51:12.242 10758 10822 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-08 18:51:12.242 10758 10822 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-08 18:51:12.243 10758 10822 W System.err: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-08 18:51:12.243 10758 10822 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-08 18:51:12.243 10758 10822 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-08 18:51:12.243 10758 10822 W System.err: 	at java.lang.Thread.run(Thread.java:818)
03-08 18:51:12.243 10758 10758 E TRYING TO GET YOUTUBE: http://www.youtube.com/embed/nJDbQIrbj8o
03-08 18:51:12.243 10758 10758 E ID:     : nJDbQIrbj8o
03-08 18:51:12.244 10758 10758 E VIDEO_FILES: NULL

**Comment by akashpopat** [comment]
It's been fixed in the last commit.

**Comment by danilaplee** [comment]
amazing to hear!
