### ISSUE TITLE
Issue extracting video

### ISSUE THREAD

**Issue by josealonsogarcia** [HaarigerHarald/android-youtubeExtractor#3]
Hi,

Congrats for your work.

I m experimenting issues extracting some kind of videos, like this:

https://www.youtube.com/watch?v=r0bzx8m1l9I

Others videos works perfectly.

Do you know what is happening here?

Thanks,

**Comment by HaarigerHarald** [comment]
Just tried that video on my phone and within the emulator and both extractions went fine. Can you enable the LOGGING flag at: https://github.com/HaarigerHarald/android-youtubeExtractor/blob/master/youtubeExtractor/src/main/java/at/huber/youtubeExtractor/YouTubeUriExtractor.java#L35 and post the logs?

**Comment by josealonsogarcia** [comment]
Hi, thanks for your quick response. Here it is:

`04-29 18:06:20.250 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:43
04-29 18:06:20.251 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:18
04-29 18:06:20.261 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:5
04-29 18:06:20.312 9005-9015/livingindie.android.humm W/art: Suspending all threads took: 39.432ms
04-29 18:06:20.323 9005-9023/livingindie.android.humm W/art: Suspending all threads took: 10.529ms
04-29 18:06:20.333 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:36
04-29 18:06:20.337 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:17
04-29 18:06:20.345 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:133
04-29 18:06:20.350 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:242
04-29 18:06:20.351 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:243
04-29 18:06:20.352 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:160
04-29 18:06:20.354 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:278
04-29 18:06:20.355 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:140
04-29 18:06:20.357 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:171
04-29 18:06:20.358 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:249
04-29 18:06:20.359 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:250
04-29 18:06:20.361 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Itag found:251
04-29 18:06:20.362 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Decipher signatures
04-29 18:06:20.363 9005-9023/livingindie.android.humm I/art: Background partial concurrent mark sweep GC freed 34191(2MB) AllocSpace objects, 63(15MB) LOS objects, 29% free, 38MB/54MB, paused 12.299ms total 110.758ms
04-29 18:06:21.015 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Decipher FunctURL: https://s.ytimg.com/yts/jsbin/player-es_ES-vflw-Jo8H/base.js
04-29 18:06:21.018 9005-9446/livingindie.android.humm D/YouTubeUriExtractor: Decipher Functname: $r
`

If helps, doing debug, inside method decipherSignature returns false because doesn't find the function:

`                mat = patMainVariable.matcher(javascriptFile);
                if (mat.find()) {
                    mainDecipherFunct = "var " + decipherFunctionName + mat.group(2);
                } else {
                    Pattern patMainFunction = Pattern.compile("(function |,)" + decipherFunctionName + "(\\((.{1,3})\\)\\{)");
                    mat = patMainFunction.matcher(javascriptFile);
                    if (!mat.find())
                        return false;
                    mainDecipherFunct = "function " + decipherFunctionName + mat.group(2);
                }
`

Thanks,

**Comment by HaarigerHarald** [comment]
Got it, forgot to escape $ within the regex. Thanks. Can you confirm that it's fixed now?

**Comment by josealonsogarcia** [comment]
Yes, is working now :)

Thousands of thanks!
