### ISSUE TITLE
APK version number wrong?

### ISSUE THREAD

**Issue by IzzySoft** [HaarigerHarald/android-youtubeExtractor#4]
The `.apk` file of the latest release listed here on Github (v1.3.0) identifies itself as v1.1:

    package: name='at.huber.youtubeDownloader' versionCode='1' versionName='1.1'

Is that intentional? A bit confusing as one might expect a newer version than already installed, but instead gets error messages from the installer ;)

**Comment by HaarigerHarald** [comment]
You are right, that was lazy :)

**Comment by IzzySoft** [comment]
Ah! So it was an "oversight" – and as I can see, it's fixed with the v1.4 release. Thanks a lot!
