### ISSUE TITLE
No more works | YtFiles is always null

### ISSUE THREAD

**Issue by KrzyShzy** [HaarigerHarald/android-youtubeExtractor#50]
Extraction not working anymore. I think YouTube changed the way they generate video stream URLs.

**Comment by ben54260** [comment]
same problem to me

**Comment by JmyW** [comment]
I checked the iOS XCDYouTubeKit is still working well. It's open source, is probably able to be referred for resolving issue here. But I have no this skill, need Mr.Harald's support.

**Comment by bogiahatay** [comment]
same problem to me

**Comment by ben54260** [comment]
I found in YouTubeExtractor.class(327~330)
```
String signature = this.decipheredSignature;
if(signature == null) {
     return null;
 }
```
signature is return null

**Comment by QuocNamIT1** [comment]
www.youtube.com/get_video_info?video_id=" + videoID + "&eurl="
					+ URLEncoder.Encode("https://youtube.googleapis.com/v/" + videoID, "UTF-8
It look like this url dows not work.

**Comment by jatashakar** [comment]
I am also getting same Error. 
Below matcher code always returning false.

So that extraction code is not executing.

 Matcher mat = patSignatureDecFunction.matcher(javascriptFile);
            if (mat.find()) {
            
            
        }
        else
        {
            return false ;
        }

**Comment by Aracher17** [comment]
@QuocNamIT1 I guess the URLs are working. 
The problem is about the matcher, I am currently searching for a better working pattern.
Stay tuned!

**Comment by Aracher17** [comment]
Yep, I found a working pattern! 
Will create a pull request soon!

**Comment by akashpopat** [comment]
@Aracher17 What should it be ?

**Comment by Aracher17** [comment]
Unfortunately, I am unable to push a new branch to this git. 
The working pattern looks like that: `"([\"\\'])signature\\1\\s*,\\s*(?<sig>[a-zA-Z0-9$]+)\\("`

I create a two-level mechanism where it checks both patterns
`private static final Pattern patSignatureDecFunction = Pattern.compile("([\"\\'])signature\\1\\s*,\\s*(?<sig>[a-zA-Z0-9$]+)\\(");
    private static final Pattern patSignatureDecFunction_2 = Pattern.compile("\\(\"signature\",(.{1,3}?)\\(.{1,10}?\\)");`

**Comment by teocci** [comment]
Yeah the signature has changed. 
(video)[https://youtube.com/watch?v=nozewQJ4hyw]

I manually extracted the signature for this video but it doesn't work. I think we have to copy the technique from (youtube_dl)[https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py] 
(download-link-worng-signature)[https://r8---sn-3u-bh2d.googlevideo.com/videoplayback?pfa=5&ctier=A&ratebypass=yes&sparams=clen%2Cctier%2Cdur%2Cei%2Cgir%2Chightc%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpcm2cms%2Cpfa%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&gir=yes&mt=1518592361&requiressl=yes&clen=6743162&key=yt6&hightc=yes&c=WEB&ei=EOKDWqz4JMKGqQH3zYKYAQ&lmt=1472052190008745&expire=1518614128&pcm2cms=yes&itag=18&mm=31%2C29&ipbits=0&mn=sn-3u-bh2d%2Csn-oguelner&source=youtube&mv=m&mime=video%2Fmp4&ms=au%2Crdu&ip=59.27.125.233&dur=226.998&fvip=1&initcwndbps=1201250&id=o-APygkrKRie3eU4KU7ruhaRIV--sr1WCkcarSOrhJzBw7&pl=16&title=Kajagoogoo-%20Too%20Shy&cpn=4PQAB0oG_hY6hRGZ&signature=5E94D78D93E472236C43DA9970E37DF16B53840.3C4458FCA36EA65E66722D286063DDEE1C1E684]

**Comment by ben54260** [comment]
@Aracher17 I changed patSignatureDecFunction to yours compile, but it crash for me

**Comment by akashpopat** [comment]
Hey I've gotten it working. I'll make a new pull request.

**Comment by akashpopat** [comment]
#51 Done!

**Comment by Aracher17** [comment]
@ben54260 
Can you provide a crash report?
I am also experiencing some difficulties

**Comment by ben54260** [comment]
@Aracher17  I copy #51 to my code, and it work. I miss to change group to 2

**Comment by ashwinisawanth412** [comment]
Same here...not working for me too...ytfiles coming null in onExtrctionComplete

**Comment by juanmoide** [comment]
When will it merge with the fix?

**Comment by bogiahatay** [comment]
please update
compile 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT'

**Comment by KrzyShzy** [comment]
This issue is fixed now. Thanks to OG HaarigerHarald, Aracher17, akashpopat and everybody else who commented.
Please update your dependency:
compile 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT'
or 
compile 'com.github.HaarigerHarald:android-youtubeExtractor:v1.7.0'

**Comment by dixit12345** [comment]
ytfiles coming null in onExtractionComplete  i am using this video  https://www.youtube.com/watch?v=JJhSOTc6ZjU  can anyone help me pls
