### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ionutcristea** [HaarigerHarald/android-youtubeExtractor#65]
Hello,
The library seems to fail in retrieving files.

**Comment by barisahmet** [comment]
Can confirm. There was a change at YouTube side, I guess. Youtube-dl has been fixed lately. Check:

https://github.com/rg3/youtube-dl/pull/17464

**Comment by JmyW** [comment]
Looks like other libraries have fixed this issue, anyone can help to transfer solution for HaarigerHarald library here?

**Comment by ionutcristea** [comment]
Fix: put this in youtube extractor
private static final Pattern patSignatureDecFunction = Pattern.compile( "(\\w+)\\s*=\\s*function\\((\\w+)\\)\\{\\s*\\2=\\s*\\2\\.split\\(\"\"\\)\\s*;");

**Comment by barisahmet** [comment]
@ionutcristea It says "Illegal escape char in string literal".

Can you share it code-formatted?

**Comment by JmyW** [comment]
My Fix sharing: (this is referred from XCD solution)
private static final Pattern patSignatureDecFunction = Pattern.compile("(\\w+)\\s*=\\s*function\\((\\w+)\\).\\s*\\2=\\s*\\2\\.split\\(\"\"\\)\\s*;");

Hopefully it helps others.

**Comment by akashpopat** [comment]
@ionutcristea Hey this didn't work for me. Can you please upload the YouTubeExtractor.java file please.

**Comment by barisahmet** [comment]
@akashpopat see https://github.com/HaarigerHarald/android-youtubeExtractor/pull/66

Thanks @JmyW

**Comment by touficbatache** [comment]
Hi @JmyW, how can I compile the library with the fix for use in my project?

**Comment by JmyW** [comment]
@touficbatache , I'm not using Gradle but manually moved those files of libs into my project. Thus, I can easily changed the pattern as what I posted above. And for sure just compile as usual.

**Comment by touficbatache** [comment]
@JmyW Thanks! I used what @barisahmet suggested [here].(https://github.com/HaarigerHarald/android-youtubeExtractor/pull/66#issuecomment-419638083)
