### ISSUE TITLE
Gradle Build Error

### ISSUE THREAD

**Issue by Sadmansamee** [HaarigerHarald/android-youtubeExtractor#7]
I'm having this error

Error:(74, 13) Failed to resolve: com.github.HaarigerHarald:android-youtubeExtractor:-SNAPSHOT
<a href="openFile:/Volumes/Work/WorkSpaces/Android_Studio/YouTubeDownloader/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

what's the fix?

**Comment by AroundPixels** [comment]
If the problem is to compile the library, have you added this code to your build.gradle file?

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}

AND

dependencies {
    compile 'com.github.HaarigerHarald:android-youtubeExtractor:v1.4.0'
}

It worked for me.

**Comment by HaarigerHarald** [comment]
Yeah, seems like you now have to explicitly tell jitpack to get the master branch:

    compile 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT'

or use the release as mentioned.

**Comment by vkdinventor** [comment]
Hi I was using com.github.HaarigerHarald:android-youtubeExtractor:-SNAPSHOT as dependency and everything was working fine. but one day suddenly I started getting error 
Failed to resolve: com.github.HaarigerHarald:android-youtubeExtractor:-SNAPSHOT so I changed to compile 'com.github.HaarigerHarald:android-youtubeExtractor:v1.4.0' but now I not able to download all videos.

**Comment by AroundPixels** [comment]
Same here, SNAPSHOT is not working, but I tried 'com.github.HaarigerHarald:android-youtubeExtractor:v1.5.0' and worked fine. Try it

**Comment by vkdinventor** [comment]
youtubeExtractor:v1.5.0' is not downloading all videos.

**Comment by AroundPixels** [comment]
Ups! For me worked for my problematic Vevo YouTube videos.Don't know it fail with other.
It will be great to be able to download the jar file if the repro has this problems :(

**Comment by vkdinventor** [comment]
I have added as a module and now its working fine.

**Comment by anson-GH** [comment]
To always build from the latest commit with all updates. Add the JitPack repository:
file path: **build.gradle**
allprojects {
    repositories {
        maven { url "https://jitpack.io" } 

    }
}

file path: **/app/build.gradle**
compile 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT'

both must have.

**Comment by surajappentus** [comment]
still showing the same error and i am using this dependency

    implementation 'com.github.HaarigerHarald:android-youtubeExtractor:v2.1.0'

**Comment by Jexzzy** [comment]
I tried Everything but Nothing is Working
