### ISSUE TITLE
Cant get sound from youtube videos

### ISSUE THREAD

**Issue by NelsonDaniel24** [HaarigerHarald/android-youtubeExtractor#75]
Example :
https://www.youtube.com/watch?v=bx-fuY7LpSU
with this video i cant get the sound. 

My code is the follow: 

  
                new YouTubeExtractor(context) {
                    @Override
                    public void onExtractionComplete(SparseArray<YtFile> files, VideoMeta vMeta) {
                        if (files != null) {

                            // 720, 1080, 480
                            List<Integer> iTags = Arrays.asList(22, 137, 18);

                            for (Integer iTag : iTags) {

                                YtFile ytFile = files.get(iTag);

                                if (ytFile != null) {

                                    String downloadUrl = ytFile.getUrl();

                                    if (downloadUrl != null && !downloadUrl.isEmpty()) {
                                        Toast.makeText(context, "LOL" + downloadUrl, Toast.LENGTH_LONG).show();
                                        return;

                                    }

                                }

                            }

                        }

                    }
                }.extract(youtubeLink, true, true);

Any solution ?

**Comment by NelsonDaniel24** [comment]
Nvm, i just realised why..
137 itag is 1080p mp4 without audio.

**Comment by eggham0518** [comment]
Did you solve this problem?

**Comment by prasanthvel** [comment]
any update on this

**Comment by SurajBahadur** [comment]
@prasanthvel  @eggham0518 @NelsonDaniel24  There is no problem with your code and kindly go through this link https://gist.github.com/SurajBahadur/57c27047b7beedaa82497fcfbd0e5eee to know which itag support both audio as well video.
