### ISSUE TITLE
Always Fail to Extract the Video since today

### ISSUE THREAD

**Issue by JmyW** [HaarigerHarald/android-youtubeExtractor#80]
Cannot extract most of video any more since a few hours ago (3/14). 
Mr. Harald, could you help? 

https://www.youtube.com/watch?v=Il-an3K9pjg
https://www.youtube.com/watch?v=kHLHSlExFis

**Comment by MCrissDev** [comment]
I think youtube changed the decryption keys again.

**Comment by HaarigerHarald** [comment]
Hi, I can't reproduce this issue both videos work fine for me. Can you run the extraction tests and post the logs?

**Comment by JmyW** [comment]
I turn LOGGING to true and gather log below. Is that what you need? (I don't quite understand what you asked to run the "extraction test" ...)
This is the test for "Il-an3K9pjg". In my app side on onExtractionComplete, received the ytFiles as "null". 

_03-15 01:05:21.189 11454-11668/com.MMBox D/YouTubeExtractor: infoUrl: https://www.youtube.com/get_video_info?video_id=Il-an3K9pjg&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FIl-an3K9pjg
03-15 01:05:21.866 11454-11668/com.MMBox D/YouTubeExtractor: Get from youtube page
03-15 01:05:22.417 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:18
03-15 01:05:22.418 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:137
03-15 01:05:22.419 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:248
03-15 01:05:22.421 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:136
03-15 01:05:22.422 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:247
03-15 01:05:22.423 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:398
03-15 01:05:22.423 11454-11668/com.MMBox D/YouTubeExtractor: Itag not in list:398
03-15 01:05:22.424 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:135
03-15 01:05:22.425 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:244
03-15 01:05:22.426 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:397
03-15 01:05:22.426 11454-11668/com.MMBox D/YouTubeExtractor: Itag not in list:397
03-15 01:05:22.428 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:134
03-15 01:05:22.430 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:243
03-15 01:05:22.432 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:396
03-15 01:05:22.432 11454-11668/com.MMBox D/YouTubeExtractor: Itag not in list:396
03-15 01:05:22.432 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:133
03-15 01:05:22.434 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:242
03-15 01:05:22.435 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:395
03-15 01:05:22.435 11454-11668/com.MMBox D/YouTubeExtractor: Itag not in list:395
03-15 01:05:22.436 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:160
03-15 01:05:22.437 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:278
03-15 01:05:22.438 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:394
03-15 01:05:22.438 11454-11668/com.MMBox D/YouTubeExtractor: Itag not in list:394
03-15 01:05:22.439 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:140
03-15 01:05:22.441 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:171
03-15 01:05:22.442 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:249
03-15 01:05:22.443 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:250
03-15 01:05:22.445 11454-11668/com.MMBox D/YouTubeExtractor: Itag found:251
03-15 01:05:22.447 11454-11668/com.MMBox D/YouTubeExtractor: Decipher signatures: 18, videos: 18
03-15 01:05:22.835 11454-11668/com.MMBox D/YouTubeExtractor: Decipher FunctURL: https://s.ytimg.com/yts/jsbin/player_ias-vflkyt12p/zh_TW/base.js
03-15 01:05:23.069 11454-11668/com.MMBox D/YouTubeExtractor: Decipher Functname: u_

**Comment by JmyW** [comment]
Not sure whether it's location/country issue. I offer more IDs which is failed in my side (Taiwan) for your try. Thanks for help in advance.

feOq6MWeUXA , l6pFa0qX9Tk , FWtbGkpdoP4 , imksLPHX1ZM

**Comment by MCrissDev** [comment]
I can reproduce the same issue as @JmyW  too.

**Comment by MCrissDev** [comment]
I tried with youtube-dl and works fine.

**Comment by JmyW** [comment]
@HaarigerHarald Thank you so much for the revision adding "$" 👍.
I tried my app this morning, it is just working without changing anything. Looks like YouTube change something back ?! However, appreciate your support. Thanks.
