### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by MCrissDev** [HaarigerHarald/android-youtubeExtractor#91]
Description

Streams like
https://www.youtube.com/watch?v=6HCnT_NqrQI do not work anymore
Steps to Reproduce

Please include the direct url to the YouTube video.

1.https://www.youtube.com/watch?v=6HCnT_NqrQI
2.https://www.youtube.com/watch?v=GIITpi-WfhA
3.https://www.youtube.com/watch?v=QmGX3t0VjJM

Expected behavior: all detected streams should work

**Comment by LowLevelSubmarine** [comment]
I have the same problem. My app can't stream any song anymore. I had some random 403 problems with the urls earlier, but now, it's broken. I hope this problem can be fixed easily, that google hasn't reworked their whole system...

**Comment by nguyendinhphuong** [comment]
i got that error too

**Comment by LowLevelSubmarine** [comment]
The problem is fixed, you can update the api and it'll work fine :) OP should close the issues... xD

**Comment by MCrissDev** [comment]
Yes, its working now. Closing this issue.

**Comment by a26364177** [comment]
still not working.
how to fix it

**Comment by nguyendinhphuong** [comment]
> still not working.
> how to fix it

you have to update new code
