### ISSUE TITLE
Can not get latest code

### ISSUE THREAD

**Issue by shihyin641** [HaarigerHarald/android-youtubeExtractor#92]
I use " implementation 'com.github.HaarigerHarald:android-youtubeExtractor:master-SNAPSHOT' " in gradle to get latest code(v1.8.0), but the code not update, is anything wrong?

I also tried "com.github.HaarigerHarald:android-youtubeExtractor:1.8.0", still~
Thanks~

**Comment by LowLevelSubmarine** [comment]
master-SNAPSHOT works for me.
Could there be something wrong with your IDE? For Intellij remove the version, wait for gradle to recognize the change, add the version again.

**Comment by shihyin641** [comment]
It's my bad T.T
