### ISSUE TITLE
some YouTube URLs not working

### ISSUE THREAD

**Issue by bunaif** [HaarigerHarald/android-youtubeExtractor#99]
for example 

https://youtu.be/GhXujCExneQ

https://youtu.be/ul1bvx2xN5Y

**Comment by bunaif** [comment]
also not work 
https://youtu.be/az3eW7vIjOU

**Comment by razar-dev** [comment]
not work
https://www.youtube.com/watch?v=Vtov0u4cwBI&feature=youtu.be

**Comment by bunaif** [comment]
There are more links that do not work, please check.

https://www.youtube.com/watch?v=8W485DcFwJk

**Comment by JmyW** [comment]
I found same issues too.

**Comment by JmyW** [comment]
There have been more URLs cannot be played. I tried to compare other solutions but cannot find clues :(

https://www.youtube.com/watch?v=W-G-RHK3WAg
https://www.youtube.com/watch?v=oTxd8iGHPbs
https://www.youtube.com/watch?v=B7wv36-LuU8
https://www.youtube.com/watch?v=-RV6UYg87nQ
https://www.youtube.com/watch?v=0yeKoZP5qQc
https://www.youtube.com/watch?v=kganr8ClEAU

**Comment by waqarr** [comment]
a lot of new youtube URLs not working. kindly update the extractor. thank you so much

**Comment by bunaif** [comment]
to fix problem open [YouTubeExtractor.java](https://github.com/HaarigerHarald/android-youtubeExtractor/blob/master/youtubeExtractor/src/main/java/at/huber/youtubeExtractor/YouTubeExtractor.java) and change this lines

`private static final Pattern patTitle = Pattern.compile("title=(.*?)(&|\\z)");`
`private static final Pattern patAuthor = Pattern.compile("author=(.+?)(&|\\z)");`
`private static final Pattern patChannelId = Pattern.compile("ucid=(.+?)(&|\\z)");`
`private static final Pattern patLength = Pattern.compile("length_seconds=(\\d+?)(&|\\z)");`
`private static final Pattern patViewCount = Pattern.compile("view_count=(\\d+?)(&|\\z)");`

`private static final Pattern patStatusOk = Pattern.compile("status=ok(&|,|\\z)");`

to
this 5 lines fixed by @razar-dev
`private static final Pattern patTitle = Pattern.compile("title%22%3A%22(.*?)(%22|\\z)");`
`private static final Pattern patAuthor = Pattern.compile("author%22%3A%22(.+?)(%22|\\z)");`
`private static final Pattern patChannelId = Pattern.compile("channelId%22%3A%22(.+?)(%22|\\z)");`
`private static final Pattern patLength = Pattern.compile("lengthSeconds%22%3A%22(\\d+?)(%22|\\z)");`
`private static final Pattern patViewCount = Pattern.compile("viewCount%22%3A%22(\\d+?)(%22|\\z)");`


`private static final Pattern patStatusOk = Pattern.compile("status=ok(%22|,|\\z)");`

**Comment by JmyW** [comment]
@bunaif , @razar-dev , Thanks a lot! It works great!

**Comment by hcode10** [comment]
Thanks it's working for me :)

**Comment by coyote66** [comment]
Hi, nice job,congratulations !,  i have problem with lot of urls, por example:
https://www.youtube.com/watch?v=bmGDIBvwrJ8
https://www.youtube.com/watch?v=CRWoR8u5LqI 
Can you help me?

Many thanks!
